### PR TITLE
Initializing Bookstore

### PR DESCRIPTION
**Pull request by CesarHerr**
- Setup a new React application using Create React App. :heavy_check_mark: 
- Create a directory for your reusable components: /components. :heavy_check_mark: 
- Install React Router V6. :heavy_check_mark: 
- Setup your router inside of App. :heavy_check_mark: 
- Add 2 routes in your application, each should render a page component:  /,  /categories. :heavy_check_mark: 
  
Create components inside of the /components directory:
- Contains individual book state, as well as a button to delete the book. :heavy_check_mark: 
- Contains a list to renders individual books. :heavy_check_mark: 
- Contains a form to create new books. :heavy_check_mark: 
- Contains a navigation to link to the 2 routes you created. :heavy_check_mark: 

- In the design you can see an input for a category - please replace it with an author. :heavy_check_mark: 
Note: Styling is NOT required at this state

[InitialBookstore.webm](https://github.com/CesarHerr/bookstore_react/assets/111262493/fa0f57e0-2bfb-483a-b96a-552e0e9fd5cc)

### CODE REVIEW

**Review by Ibizugbe — COMMENTED** [review]
Hi @CesarHerr 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have linters setup. Kindly setup linters on your project and resubmit👍.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by CesarHerr** [comment]
@Ibizugbe You are right! I made a mistake on the folder name for the GitHub actions, I already fix it! Thanks

**Review by OLIPLICHE — APPROVED** [review]
Hi @CesarHerr, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Set up routing using React Router(✅)) 👏
- The App contains two pages `Books` and `Categories`👏
- Contains navigation to link to the 2 routes👏 👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by CesarHerr** [comment]
@OLIPLICHE  Thanks for your review! ✌

**Pull request merged**
